# Generated by Django 3.1.5 on 2024-01-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipe_name', models.CharField(max_length=100)),
                ('receipe_desc', models.TextField()),
                ('receipe_img', models.ImageField(upload_to='imgs')),
            ],
        ),
    ]
