# Generated by Django 4.2.9 on 2024-02-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipe", "0002_receipe_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipe",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
